include:
  - board: nice_nano//zmk
    shield: temper_left nice_view_adapter nice_view
  - board: nice_nano//zmk
    shield: temper_right nice_view_adapter nice_view
  - board: nice_nano//zmk
    shield: settings_reset
